version: "3"

services:
  springboot:
    image: registry.cn-chengdu.aliyuncs.com/1s/springboot
    volumes:
      - "./:/opt/jar"
    working_dir: /opt/jar
    container_name: java_test
#    restart: always
    environment:
      - ENTRYPOINT=nohup java -Dfile.encoding=UTF-8 -Xmx1000m -Xms600m -Duser.timezone=GMT+8  hello.java
      